### ISSUE TITLE
合并？

### ISSUE THREAD

**Issue by jwnhy** [shigexiaohao/SUSTechWtf#2]
我是SUSTech WTF的域名所有者也是那个gitbook的创建者，不知道是否愿意将这两个项目合并，一方面记录各大事件，另一方面提供一个渠道提出proposal

**Comment by shigexiaohao** [comment]
好鸭！

**Comment by jwnhy** [comment]
那么问题来了，咋整Orz，我直接把gitbook同步到这个仓库么？感觉会冲突。。。

**Comment by jwnhy** [comment]
https://github.com/JohnWestonNull/SUSTech.WTF/invitations

**Comment by shigexiaohao** [comment]
🤔要不网站那部分代码还是分开。我把你加到这个项目来，把wtf网站介绍和链接放到这边？这样维护可能方便一点

**Comment by shigexiaohao** [comment]
我发邀请啦，邮件查收

**Comment by tempest2023** [comment]
建议和http://sustech.icu/联动
